### ISSUE TITLE
Erroneous link when using "FFImageChooser" without selecting a specified model and/or revision

### ISSUE THREAD

**Issue by flxai** [freifunkks/moinmoin-plugins#1]
When using the plugin "FFImageChooser" (e.g. [here](https://ffks.de/Firmware/)) and clicking the download button at the end, while not selecting any router model and/or revision, the link redirection is wrong.
The link generated without any information is:
https://freifunk-kassel.de/images/stable/factory/gluon-ffks-2015.02.07.11--.bin

Therefore it would be best if we do the following:
1. Let the URL rewrite script check for parameters as needed, and redirect to the download page, if they were not specified.
2. Use Javascript on the firmware download page to initially disable the download button and only enable it when the needed parameters have been set.

**Comment by jplatte** [comment]
Okay, so I could change the PHP script if we really want to do that...

Do you think it's hard to just rewrite it in Python so we don't additionally need PHP anymore? Because I think it's a bit better to just rewrite that tiny thing and fix the bug in the Python version.

**Comment by jplatte** [comment]
Oops...

**Comment by flxai** [comment]
Either of us can rewrite the PHP to Python sometime soon.

**Comment by jplatte** [comment]
I still don't like Python ^^

How about you do the Python (server) side and I do the JS?

**Comment by jplatte** [comment]
Ugh, apparently an issue can only be assigned to a single person. Well, whatever...

**Comment by jplatte** [comment]
Fixed by 3a6c2b3d94199fd0b8de53e1a93cb3b542dc484d.
