### ISSUE TITLE
Improve firmware download UX

### ISSUE THREAD

**Issue by jplatte** [freifunkks/moinmoin-plugins#3]
- [x] Fix #1
- [x] Make vendor dropdowns collapsable by clicking on them again
- [x] ~~Add some sort of quicker way to the download after the user selected a router model~~
- [x] ~~Have the download button disabled until the user actually selecter a router model~~

The two striked through items were not done because we found a better solution:
Removing the download button, and making the router model version (if existing) or router model a direct link to the stable firmware for that router model (+version).

**Comment by flxai** [comment]
What do you think of the suggestion, seen in the attachment?
![amj5le](https://cloud.githubusercontent.com/assets/10831300/8874925/c13dbeaa-3215-11e5-8d84-2de0174035ec.gif)

I think this would alleviate the pain of seeing the page scrolling down.
We would only need to insert download buttons every row, which would scroll down like the vendors menu.

**Comment by jplatte** [comment]
As this is JS-only, we wouldn't need to insert download buttons every row. I also can't think of a good CSS-only solution, so yeah, implementation-wise this isn't really a problem. But design-wise, I don't like it TBH. I think the solution I like most so far is having some sort of sticky footer with the button(s) in it.

**Comment by jplatte** [comment]
Okay, first item done! :)

I added the according js file to the theme repo, as I didn't know whether I could just add a wikistatic folder here as well or something like that. [The file](https://github.com/freifunkks/moinmoin-theme/blob/master/wikistatic/ffks/js/firmware-dl.js) should be moved into this repo though if that's easily possible.

**Comment by jplatte** [comment]
All done!
